version: 2

jobs:
  test-construct:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - run: npm install

      - run: npm run lint-check

      - run: npm run test

  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - run: npm install

      - run: npm run compile

      - run: cp package.json ./build/package.json

      - run: cp README.md ./build/README.md

      - run: cd ./build && ls -alR

      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: ~/repo

      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/repo/.npmrc

      - run: cd ./build && npm --userconfig="../.npmrc" publish

workflows:
  version: 2
  build-and-publish:
    jobs:
      - test-construct:
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
      - build:
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
      - publish:
          requires:
            - test-construct
            - build
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
